version: '3'
services:
  s3-mount:
    build: .
    entrypoint:
      - sh
      - -c
    command: "mkdir -p /s3 && mount-s3 s3-mountpoint-bucket-xyz /s3 && while true; do echo s3-mount running in the background..; sleep 10; done"